// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAznqLALHEBBm0PAT1nwPUnnwXAC-AyCyg',
    appId: '1:655081648854:web:8db17978c2ad1be03fcf77',
    messagingSenderId: '655081648854',
    projectId: 'safara-a7e4e',
    authDomain: 'safara-a7e4e.firebaseapp.com',
    storageBucket: 'safara-a7e4e.firebasestorage.app',
    measurementId: 'G-L6CL9977ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjw0_S-06Dovlzg7OBOKgdC20NM8HL2q8',
    appId: '1:655081648854:android:7fad6c4b0626f0ae3fcf77',
    messagingSenderId: '655081648854',
    projectId: 'safara-a7e4e',
    storageBucket: 'safara-a7e4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPGcMXwC77TtVUHu_imArbSkevZcP3r9w',
    appId: '1:655081648854:ios:75d74a0b5e4f10d63fcf77',
    messagingSenderId: '655081648854',
    projectId: 'safara-a7e4e',
    storageBucket: 'safara-a7e4e.firebasestorage.app',
    iosBundleId: 'com.safara.safara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPGcMXwC77TtVUHu_imArbSkevZcP3r9w',
    appId: '1:655081648854:ios:75d74a0b5e4f10d63fcf77',
    messagingSenderId: '655081648854',
    projectId: 'safara-a7e4e',
    storageBucket: 'safara-a7e4e.firebasestorage.app',
    iosBundleId: 'com.safara.safara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAznqLALHEBBm0PAT1nwPUnnwXAC-AyCyg',
    appId: '1:655081648854:web:a55441a9b2407fc03fcf77',
    messagingSenderId: '655081648854',
    projectId: 'safara-a7e4e',
    authDomain: 'safara-a7e4e.firebaseapp.com',
    storageBucket: 'safara-a7e4e.firebasestorage.app',
    measurementId: 'G-LRGZQST8M0',
  );
}
